/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { workspaceUsersUpdate } from "../../funcs/workspaceUsersUpdate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateWorkspaceUserRequest$inboundSchema,
};

export const tool$workspaceUsersUpdate: ToolDefinition<typeof args> = {
  name: "workspace-users-update",
  description: `Updates the specified user's role

This operation updates the specified user's role in the workspace. Users within the account are considered "Internal" and may be assigned any role. Users outside the account are considered "External" and may only be assigned "External" roles.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await workspaceUsersUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
